# main.py
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from typing import Any, Dict, Optional

from youtube_transcript_api import (
    YouTubeTranscriptApi,
    TranscriptsDisabled,
    NoTranscriptFound,
    VideoUnavailable,
)

app = FastAPI()


def extract_youtube_id(url: str) -> Optional[str]:
    url = (url or "").strip()
    if not url:
        return None

    # youtu.be/<id>
    if "youtu.be/" in url:
        vid = url.split("youtu.be/")[1].split("?")[0].split("&")[0].strip()
        return vid or None

    # youtube.com/watch?v=<id>
    if "watch?v=" in url:
        vid = url.split("watch?v=")[1].split("&")[0].strip()
        return vid or None

    # youtube.com/shorts/<id>
    if "/shorts/" in url:
        vid = url.split("/shorts/")[1].split("?")[0].split("&")[0].strip()
        return vid or None

    return None


@app.get("/")
def health():
    return {"ok": True, "service": "tradementor-transcript-service"}


@app.post("/transcript")
async def transcript(request: Request):
    """
    Accepts:
      - JSON: { "url": "...", "lang": "en" }
      - form-data: url=...&lang=en
    Returns:
      { ok: true, videoId, language, transcriptText, segments }
    """
    # --- Parse body (JSON OR form) ---
    url = None
    lang = None

    content_type = (request.headers.get("content-type") or "").lower()

    try:
        if "application/json" in content_type:
            body = await request.json()
            url = body.get("url")
            lang = body.get("lang")
        else:
            form = await request.form()
            url = form.get("url")
            lang = form.get("lang")
    except Exception:
        # If parsing fails, return a clean error
        return JSONResponse(
            status_code=400,
            content={"ok": False, "code": "BAD_REQUEST", "message": "Invalid request body. Send JSON or form-data with `url`."},
        )

    url = (url or "").strip()
    lang = (lang or "en").strip()

    if not url:
        return JSONResponse(
            status_code=400,
            content={"ok": False, "code": "MISSING_URL", "message": "Missing `url` field."},
        )

    video_id = extract_youtube_id(url)
    if not video_id:
        return JSONResponse(
            status_code=400,
            content={"ok": False, "code": "BAD_URL", "message": "Could not extract YouTube video id from URL."},
        )

    # --- Transcript fetch with fallbacks ---
    try:
        transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)

        # Preferred language fallbacks
        preferred = []
        if lang:
            preferred.append(lang)
        # common English variants if user requested "en"
        if lang == "en":
            preferred += ["en-US", "en-GB"]

        chosen = None

        # 1) Try manually created first
        for code in preferred:
            try:
                chosen = transcript_list.find_manually_created_transcript([code])
                break
            except Exception:
                pass

        # 2) Try autogenerated next
        if chosen is None:
            for code in preferred:
                try:
                    chosen = transcript_list.find_generated_transcript([code])
                    break
                except Exception:
                    pass

        # 3) If still nothing, just pick the first available transcript
        if chosen is None:
            chosen = next(iter(transcript_list))

        segments = chosen.fetch()  # list of {text, start, duration}
        text = "\n".join([s.get("text", "") for s in segments]).strip()

        return {
            "ok": True,
            "videoId": video_id,
            "language": getattr(chosen, "language_code", None),
            "transcriptText": text,
            "segments": segments,
        }

    except TranscriptsDisabled:
        return JSONResponse(
            status_code=200,
            content={"ok": False, "code": "NO_CAPTIONS", "message": "This video has captions disabled. Use Whisper mode for audio transcription."},
        )
    except NoTranscriptFound:
        return JSONResponse(
            status_code=200,
            content={"ok": False, "code": "NO_TRANSCRIPT", "message": "No transcript found for this video (no CC / no supported tracks). Use Whisper mode."},
        )
    except VideoUnavailable:
        return JSONResponse(
            status_code=200,
            content={"ok": False, "code": "VIDEO_UNAVAILABLE", "message": "Video unavailable (region/private/removed)."},
        )
    except Exception as e:
        # Unknown error: return message so you can see what happened in your UI
        return JSONResponse(
            status_code=200,
            content={"ok": False, "code": "UNKNOWN", "message": str(e)},
        )
